name: "CD"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    uses: ./.github/workflows/Publish-Image.yaml
    with:
      artifact-prefix: coco
      amd64-output: .#coco-image-linux-amd64
      arm64-output: .#coco-image-linux-arm64
      sha-tag-prefix: sha
      publish-latest-on-main: true
      publish-git-tag: true
      publish-sources: ${{ github.event_name == 'release' }}
    secrets: inherit
